# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jon Duelfer"
footer_title: "Contact"
email: jdduelfer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer, Linguist, and Settler of Catan
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  jduelfer

# Build settings
markdown: kramdown

minima:
  date_format: "%b %-d, %Y"

header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
